name: online_exam
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.4
  get_it: ^7.6.0
  go_router: ^14.2.0
  injectable: ^2.6.0
  json_annotation: ^4.8.0
  logger: ^2.0.2
  retrofit: ^4.8.0
  shared_preferences: ^2.2.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  injectable_generator: ^2.6.1
  json_serializable: ^6.7.1
  retrofit_generator: ^10.0.1
  intl_utils: ^2.8.2

flutter:
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.otf
          weight: 400
        - asset: assets/fonts/Inter-Medium.otf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Inter-Bold.otf
          weight: 700
flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  output_dir: lib/generated